name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run-job:
        description: Run Specific Job
        type: boolean
        required: false
      custom_message:
        description: Enter a custom message
        type: string
        required: true
        
env:
  DEBUG: true
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: |
          echo "Custom message: $MESSAGE"
        env:
          MESSAGE: ${{ inputs.custom_message }}
          
      - name: Printing run-job boolean value
        run: |
        if: ${{ github.event.inputs.run-job == 'true' }}
          echo ${{ inputs.run-job }}
      
